language: julia
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("QuadProg"); Pkg.test("QuadProg"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("QuadProg")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
